name: Build and deploy JAR app to Azure Web App - web-app-service-without-connection

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build using Maven
        run: mvn clean install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ env.PROD_URL }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-no-connection'
          slot-name: 'Production'
          publish-profile: <publishData><publishProfile profileName="app-no-connection - Web Deploy" publishMethod="MSDeploy" publishUrl="app-no-connection.scm.azurewebsites.net:443" msdeploySite="app-no-connection" userName="$app-no-connection" userPWD="tC5hkjL9bnKs2Emqez2E4j2Dh3tNsmS4YGxwvubY2Zcp1JupQtKPthzLZplQ" destinationAppUrl="https://app-no-connection.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="app-no-connection - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-435.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="app-no-connection\$app-no-connection" userPWD="tC5hkjL9bnKs2Emqez2E4j2Dh3tNsmS4YGxwvubY2Zcp1JupQtKPthzLZplQ" destinationAppUrl="https://app-no-connection.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="app-no-connection - Zip Deploy" publishMethod="ZipDeploy" publishUrl="app-no-connection.scm.azurewebsites.net:443" userName="$app-no-connection" userPWD="tC5hkjL9bnKs2Emqez2E4j2Dh3tNsmS4YGxwvubY2Zcp1JupQtKPthzLZplQ" destinationAppUrl="https://app-no-connection.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: '*.war'
